name: Sync Docker Hub vaulthub to GHCR
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: 原生安装Skopeo工具
        run: sudo apt update && sudo apt install -y skopeo
      - name: 登录Docker Hub源仓库
        run: skopeo login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录GitHub GHCR目标仓库
        run: skopeo login ghcr.io -u q807738511 -p ${{ secrets.GH_TOKEN }}
      - name: 全量同步vaulthub镜像
        run: |
          skopeo copy --all \
          docker://docker.io/q807738511/vaulthub:latest \
          docker://ghcr.io/q807738511/vaulthub:latest
